// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTicketSystem.Infrastructure.Persistence;

#nullable disable

namespace SupportTicketSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805031336_SuperAdmin")]
    partial class SuperAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstimatedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories", (string)null);
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Address = "Jl. Jenderal Sudirman No. 10, Jakarta Pusat, DKI Jakarta",
                            CreatedAt = new DateTime(2026, 6, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@company.com",
                            IsActive = true,
                            JobTitle = "Administrator",
                            Name = "Super Admin",
                            PasswordHash = "$2a$11$fi7TEATv4vtZHPxzFKEI7ueFFFrb29zLM45cr6bPhgOztUmn0oS5W",
                            PhoneNumber = "0812-3456-7890",
                            Role = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Jl. Jenderal Sudirman No. 10, Jakarta Pusat, DKI Jakarta",
                            CreatedAt = new DateTime(2026, 6, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@company.com",
                            IsActive = true,
                            JobTitle = "System Administrator",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$8wvhMRhDF0Cr07JsJvw2p.Vtm73a/8niPYtuY.eN.7jr66AdjWj6G",
                            PhoneNumber = "0812-3456-7890",
                            Role = "Manager",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andi.pratama@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Andi Pratama",
                            PasswordHash = "$2a$11$Rc/YPi/V.YZRPdDVOoFZl.4mx.y0wBconDL2pAiK9.WGm1vjuFvN6",
                            PhoneNumber = "0812-3456-7891",
                            Role = "SupportAgent",
                            Username = "andi.pratama"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "siti.aisyah@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Siti Aisyah",
                            PasswordHash = "$2a$11$A9Bxmn/Nht1xdLfS7Zc2/OCF/HjK2LHQ1W4g1zlHvPEP/MEl51T/G",
                            PhoneNumber = "0812-3456-7892",
                            Role = "SupportAgent",
                            Username = "siti.aisyah"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "budi.santoso@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Budi Santoso",
                            PasswordHash = "$2a$11$Q1KbGZvcNzP6qg0E.Ttwe.Bje6aJ6jOTf2u1fN2mZ/1jaItpB5VZm",
                            PhoneNumber = "0812-3456-7893",
                            Role = "SupportAgent",
                            Username = "budi.santoso"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dewi.lestari@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Dewi Lestari",
                            PasswordHash = "$2a$11$I2ay5uWFvYJjaALqa96LAesoDAXQdNlDRtt44giUN0GDjzbrRqAbO",
                            PhoneNumber = "0812-3456-7894",
                            Role = "SupportAgent",
                            Username = "dewi.lestari"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 6, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "rizky.hidayat@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Rizky Hidayat",
                            PasswordHash = "$2a$11$8PcVLLhZVRChldP.f/Y4sO/4GqfEyBUrzTyCGJC.c4QKZG1nGKJYm",
                            PhoneNumber = "0812-3456-7895",
                            Role = "SupportAgent",
                            Username = "rizky.hidayat"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nanda.triana@company.com",
                            IsActive = true,
                            JobTitle = "Support Manager",
                            Name = "Nanda Triana",
                            PasswordHash = "$2a$11$7YPLNE7IM0vVVddTSNt1AuHXA157mNmzF2CLDlaqX5hetwPLgYZLO",
                            PhoneNumber = "0812-3456-7896",
                            Role = "Manager",
                            Username = "nanda.triana"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "support@company.com",
                            IsActive = false,
                            Name = "Support Team",
                            PasswordHash = "$2a$11$/KRCzU3Xw9KsvYR.OGR7aOEsQMnEg6thz5Fu4tkZ1.YJLCuAotZ3.",
                            Role = "SupportAgent",
                            Username = "support.team"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportTicketSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Histories")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
