// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTicketSystem.Infrastructure.Persistence;

#nullable disable

namespace SupportTicketSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725145142_RemoveDuplicateTicketDateColumnsFromTicketEntity")]
    partial class RemoveDuplicateTicketDateColumnsFromTicketEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.HasIndex("CreatedAt", "Status", "AssignedTo");

                    b.ToTable("Tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 24, 14, 51, 40, 146, DateTimeKind.Utc).AddTicks(1349),
                            CustomerEmail = "john@client.com",
                            CustomerName = "John Doe",
                            Description = "Urgent: Server is not responding.",
                            Status = "Open",
                            TicketNumber = "TKT-00001",
                            Title = "System Down"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 25, 2, 51, 40, 146, DateTimeKind.Utc).AddTicks(1370),
                            CustomerEmail = "jane@client.com",
                            CustomerName = "Jane Smith",
                            Description = "Button color is wrong on dark mode.",
                            Status = "InProgress",
                            TicketNumber = "TKT-00002",
                            Title = "UI Bug"
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 22, 14, 51, 40, 146, DateTimeKind.Utc).AddTicks(1374),
                            CustomerEmail = "mark@client.com",
                            CustomerName = "Mark Lee",
                            Description = "User forgot password.",
                            Status = "Closed",
                            TicketNumber = "TKT-00003",
                            Title = "Password Reset"
                        },
                        new
                        {
                            Id = new Guid("f9eda27a-109d-41e0-a9e2-d3f8f3466a96"),
                            AssignedTo = new Guid("e5f6a7b8-c9d0-4e1f-b2a3-b4c5d6e7f8a9"),
                            CreatedAt = new DateTime(2026, 7, 25, 9, 51, 40, 146, DateTimeKind.Utc).AddTicks(1410),
                            CustomerEmail = "emily@client.com",
                            CustomerName = "Emily Blunt",
                            Description = "Credit card rejected.",
                            Status = "InProgress",
                            TicketNumber = "TKT-00004",
                            Title = "Payment Issue"
                        },
                        new
                        {
                            Id = new Guid("4aac1410-ea76-4ad0-b9b1-2c85b60eaa4e"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 23, 14, 51, 40, 146, DateTimeKind.Utc).AddTicks(1413),
                            CustomerEmail = "kevin@client.com",
                            CustomerName = "Kevin Hart",
                            Description = "CSV export is empty.",
                            Status = "Resolved",
                            TicketNumber = "TKT-00005",
                            Title = "Export Failure"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eac5c32e-6975-4447-9873-18e71281566d"),
                            Action = "Created",
                            ChangedBy = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 146, DateTimeKind.Local).AddTicks(8083),
                            NewStatus = "Open",
                            TicketId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 7, 24, 14, 51, 40, 146, DateTimeKind.Utc).AddTicks(8101)
                        },
                        new
                        {
                            Id = new Guid("56a16890-63fe-4072-9b0b-8cce81e68090"),
                            Action = "Assigned",
                            ChangedBy = new Guid("c3d4e5f6-a7b8-4c9d-8e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 146, DateTimeKind.Local).AddTicks(8104),
                            NewStatus = "InProgress",
                            TicketId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            Timestamp = new DateTime(2026, 7, 25, 4, 51, 40, 146, DateTimeKind.Utc).AddTicks(8117)
                        },
                        new
                        {
                            Id = new Guid("2dda9a3d-0e45-4677-9b7a-ae8fc32643bb"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 146, DateTimeKind.Local).AddTicks(8118),
                            NewStatus = "Closed",
                            PreviousStatus = "InProgress",
                            TicketId = new Guid("e3333333-3333-3333-3333-333333333333"),
                            Timestamp = new DateTime(2026, 7, 25, 12, 51, 40, 146, DateTimeKind.Utc).AddTicks(8122)
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 147, DateTimeKind.Local).AddTicks(684),
                            Email = "azwar@support.com",
                            Name = "Azwar Manager",
                            PasswordHash = "$2a$11$N0aoXbxp/Kxc.8Sy0WpqRuyG5PRgc2yXJ7YqccLZimchZN/37m7Em",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-8e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 253, DateTimeKind.Local).AddTicks(508),
                            Email = "sarah.m@support.com",
                            Name = "Sarah Miller",
                            PasswordHash = "$2a$11$lrYkuSGoVflai2/DyghSyOYrsh3YBrs/n6RHOyxHFK1F2Iz0oLOGa",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-9f2a-3b4c5d6e7f8a"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 359, DateTimeKind.Local).AddTicks(1423),
                            Email = "david.c@support.com",
                            Name = "David Chen",
                            PasswordHash = "$2a$11$AHsqqbzy0m7F5A8i1D.pgu7xIWiXvkG89vePJlNCAK4gWsjwR.HJu",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 464, DateTimeKind.Local).AddTicks(5986),
                            Email = "budi@support.com",
                            Name = "Budi Agent",
                            PasswordHash = "$2a$11$6nEynZ9aN6TGCfNfCsfXG.OMALh4wZ05./hdZCp.OeU16yA3CaN6K",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-b2a3-b4c5d6e7f8a9"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 569, DateTimeKind.Local).AddTicks(427),
                            Email = "alice.j@support.com",
                            Name = "Alice Johnson",
                            PasswordHash = "$2a$11$8P7OX.I6TlhaqnxO9sgK7OG4R1mnyE2JB1cpeduOsuN/cRcYjAaBe",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4f2a-c3b4-c5d6e7f8a9b0"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 673, DateTimeKind.Local).AddTicks(9135),
                            Email = "robert.s@support.com",
                            Name = "Robert Smith",
                            PasswordHash = "$2a$11$4DgyzAPRzJ8s82wQKlITx.Y8DcFzN5HdkyK6MkWlwi.E1eoTnaC1a",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 780, DateTimeKind.Local).AddTicks(4781),
                            Email = "emily.d@support.com",
                            Name = "Emily Davis",
                            PasswordHash = "$2a$11$o57C7LlmS3tspQLBoW8VpulAziG12FSlA/cnXNfPKup4UEKqw718C",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("1b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 886, DateTimeKind.Local).AddTicks(4531),
                            Email = "michael.b@support.com",
                            Name = "Michael Brown",
                            PasswordHash = "$2a$11$Yn4M3HHdmw8Rblzq3jaWhedKzvp7a.10CVTy5BAIIWv6pbQ0eV92G",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 40, 992, DateTimeKind.Local).AddTicks(1933),
                            Email = "jessica.w@support.com",
                            Name = "Jessica Wilson",
                            PasswordHash = "$2a$11$VfIEcel2EoL6XFWBVQJdmOT9x..9kARerLb4/ULXzEtWhiMAMxDom",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("3d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
                            CreatedAt = new DateTime(2026, 7, 25, 21, 51, 41, 97, DateTimeKind.Local).AddTicks(8028),
                            Email = "kevin.l@support.com",
                            Name = "Kevin Lee",
                            PasswordHash = "$2a$11$ZNAYuwTD2p72o5idHzBPp.BKwvoS9J.yllThCrBe2cpUAPEka6q4q",
                            Role = "SupportAgent"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportTicketSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
