// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTicketSystem.Infrastructure.Persistence;

#nullable disable

namespace SupportTicketSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723055054_AddTicketSeedDataForTesting")]
    partial class AddTicketSeedDataForTesting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 22, 5, 50, 53, 594, DateTimeKind.Utc).AddTicks(87),
                            CustomerEmail = "john@client.com",
                            CustomerName = "John Doe",
                            Description = "Urgent: Server is not responding.",
                            Status = "Open",
                            TicketNumber = "TKT-00001",
                            Title = "System Down"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 22, 17, 50, 53, 594, DateTimeKind.Utc).AddTicks(106),
                            CustomerEmail = "jane@client.com",
                            CustomerName = "Jane Smith",
                            Description = "Button color is wrong on dark mode.",
                            Status = "InProgress",
                            TicketNumber = "TKT-00002",
                            Title = "UI Bug"
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 20, 5, 50, 53, 594, DateTimeKind.Utc).AddTicks(110),
                            CustomerEmail = "mark@client.com",
                            CustomerName = "Mark Lee",
                            Description = "User forgot password.",
                            Status = "Closed",
                            TicketNumber = "TKT-00003",
                            Title = "Password Reset"
                        },
                        new
                        {
                            Id = new Guid("939be3ad-6997-4e92-9724-e06191b9978c"),
                            AssignedTo = new Guid("e5f6a7b8-c9d0-4e1f-b2a3-b4c5d6e7f8a9"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 50, 53, 594, DateTimeKind.Utc).AddTicks(138),
                            CustomerEmail = "emily@client.com",
                            CustomerName = "Emily Blunt",
                            Description = "Credit card rejected.",
                            Status = "InProgress",
                            TicketNumber = "TKT-00004",
                            Title = "Payment Issue"
                        },
                        new
                        {
                            Id = new Guid("1d9c3923-e771-4b54-8a3c-c8955f18b35f"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 21, 5, 50, 53, 594, DateTimeKind.Utc).AddTicks(141),
                            CustomerEmail = "kevin@client.com",
                            CustomerName = "Kevin Hart",
                            Description = "CSV export is empty.",
                            Status = "Resolved",
                            TicketNumber = "TKT-00005",
                            Title = "Export Failure"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5bd5fc0-5a77-486e-bc93-c7bfef492444"),
                            Action = "Created",
                            ChangedBy = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(5360),
                            NewStatus = "Open",
                            TicketId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 7, 22, 5, 50, 53, 594, DateTimeKind.Utc).AddTicks(5379)
                        },
                        new
                        {
                            Id = new Guid("0e669024-e40b-4a0f-a80d-a2874fff6f57"),
                            Action = "Assigned",
                            ChangedBy = new Guid("c3d4e5f6-a7b8-4c9d-8e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(5381),
                            NewStatus = "InProgress",
                            TicketId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            Timestamp = new DateTime(2026, 7, 22, 19, 50, 53, 594, DateTimeKind.Utc).AddTicks(5383)
                        },
                        new
                        {
                            Id = new Guid("e512de76-4d2e-4845-a3f5-f1fa7d06650c"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(5385),
                            NewStatus = "Closed",
                            PreviousStatus = "InProgress",
                            TicketId = new Guid("e3333333-3333-3333-3333-333333333333"),
                            Timestamp = new DateTime(2026, 7, 23, 3, 50, 53, 594, DateTimeKind.Utc).AddTicks(5387)
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7621),
                            Email = "azwar@support.com",
                            Name = "Azwar Manager",
                            PasswordHash = "hashed_pass",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-8e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7630),
                            Email = "sarah.m@support.com",
                            Name = "Sarah Miller",
                            PasswordHash = "hashed_pass",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-9f2a-3b4c5d6e7f8a"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7631),
                            Email = "david.c@support.com",
                            Name = "David Chen",
                            PasswordHash = "hashed_pass",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7634),
                            Email = "budi@support.com",
                            Name = "Budi Agent",
                            PasswordHash = "hashed_pass",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-b2a3-b4c5d6e7f8a9"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7636),
                            Email = "alice.j@support.com",
                            Name = "Alice Johnson",
                            PasswordHash = "hashed_pass",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4f2a-c3b4-c5d6e7f8a9b0"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7637),
                            Email = "robert.s@support.com",
                            Name = "Robert Smith",
                            PasswordHash = "hashed_pass",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7640),
                            Email = "emily.d@support.com",
                            Name = "Emily Davis",
                            PasswordHash = "hashed_pass",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("1b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7642),
                            Email = "michael.b@support.com",
                            Name = "Michael Brown",
                            PasswordHash = "hashed_pass",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7645),
                            Email = "jessica.w@support.com",
                            Name = "Jessica Wilson",
                            PasswordHash = "hashed_pass",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("3d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
                            CreatedAt = new DateTime(2026, 7, 23, 12, 50, 53, 594, DateTimeKind.Local).AddTicks(7647),
                            Email = "kevin.l@support.com",
                            Name = "Kevin Lee",
                            PasswordHash = "hashed_pass",
                            Role = "SupportAgent"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportTicketSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
