// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTicketSystem.Infrastructure.Persistence;

#nullable disable

namespace SupportTicketSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725173706_AlignEntitiesWithUpdatedDesign")]
    partial class AlignEntitiesWithUpdatedDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstimatedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Application = "InternalPortal",
                            AssignedTo = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Access",
                            CreatedAt = new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "budi.hartono@customer.com",
                            CustomerName = "Budi Hartono",
                            CustomerPhone = "0812-3456-7801",
                            Description = "User tidak bisa login setelah update aplikasi versi terbaru. Muncul pesan 'Invalid credentials' meskipun password sudah benar.",
                            Impact = "SingleUser",
                            Priority = "High",
                            Status = "Open",
                            TicketNumber = "TKT-00001",
                            Title = "Login gagal pada aplikasi",
                            Type = "Incident"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Application = "FileServer",
                            AssignedTo = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Application",
                            CreatedAt = new DateTime(2026, 6, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "siti.nurhaliza@customer.com",
                            CustomerName = "Siti Nurhaliza",
                            CustomerPhone = "0812-3456-7802",
                            Description = "Dokumen gagal terupload dengan pesan error 'File size exceeded' padahal ukuran file di bawah batas maksimal.",
                            Impact = "SomeUsers",
                            Priority = "Medium",
                            Status = "InProgress",
                            TicketNumber = "TKT-00002",
                            Title = "Error saat upload dokumen",
                            Type = "Incident"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Application = "ERP",
                            Category = "Access",
                            CreatedAt = new DateTime(2026, 6, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "rizky.kurniawan@customer.com",
                            CustomerName = "Rizky Kurniawan",
                            CustomerPhone = "0812-3456-7803",
                            Description = "Membutuhkan akses ke modul laporan keuangan untuk keperluan audit bulanan.",
                            Impact = "SingleUser",
                            Priority = "Medium",
                            Status = "Open",
                            TicketNumber = "TKT-00003",
                            Title = "Permintaan akses baru",
                            Type = "ServiceRequest"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Application = "CRM",
                            AssignedTo = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Application",
                            ClosedAt = new DateTime(2026, 6, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "dewi.lestari@customer.com",
                            CustomerName = "Dewi Lestari",
                            CustomerPhone = "0812-3456-7804",
                            Description = "Saat melakukan penyimpanan data pelanggan baru pada modul CRM, sistem menampilkan pesan error 'Failed to save data' dan data tidak tersimpan di database.",
                            Impact = "SomeUsers",
                            Priority = "Low",
                            Status = "Closed",
                            TicketNumber = "TKT-00004",
                            Title = "Data tidak tersimpan",
                            Type = "Incident"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Application = "ERP",
                            AssignedTo = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Report",
                            ClosedAt = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "andika.putra@customer.com",
                            CustomerName = "Andika Putra",
                            CustomerPhone = "0812-3456-7805",
                            Description = "Laporan penjualan bulanan tidak muncul di dashboard, sudah dicoba refresh berkali-kali.",
                            Impact = "SingleUser",
                            Priority = "Low",
                            Status = "Closed",
                            TicketNumber = "TKT-00005",
                            Title = "Laporan tidak muncul",
                            Type = "Incident"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Application = "CRM",
                            AssignedTo = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Application",
                            CreatedAt = new DateTime(2026, 6, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "it@majusejahtera.com",
                            CustomerName = "PT. Maju Sejahtera",
                            CustomerPhone = "021-5551234",
                            Description = "Integrasi API antara sistem internal dengan CRM Elnusa mengembalikan error 500 sejak pagi ini.",
                            Impact = "AllUsers",
                            Priority = "High",
                            Status = "InProgress",
                            TicketNumber = "TKT-00006",
                            Title = "Integrasi API gagal",
                            Type = "Incident"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Application = "InternalPortal",
                            AssignedTo = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Application",
                            CreatedAt = new DateTime(2026, 6, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "joko.susilo@customer.com",
                            CustomerName = "Joko Susilo",
                            CustomerPhone = "0812-3456-7807",
                            Description = "Aplikasi terasa sangat lambat saat membuka halaman dashboard, terutama di jam sibuk.",
                            Impact = "AllUsers",
                            Priority = "Medium",
                            Status = "Open",
                            TicketNumber = "TKT-00007",
                            Title = "Aplikasi lambat",
                            Type = "Problem"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Application = "Email",
                            AssignedTo = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Access",
                            ClosedAt = new DateTime(2026, 6, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 6, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "rina.wulandari@customer.com",
                            CustomerName = "Rina Wulandari",
                            CustomerPhone = "0812-3456-7808",
                            Description = "Lupa password dan tidak menerima email reset password setelah beberapa kali percobaan.",
                            Impact = "SingleUser",
                            Priority = "Low",
                            Status = "Closed",
                            TicketNumber = "TKT-00008",
                            Title = "Reset password user",
                            Type = "ServiceRequest"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            Application = "ERP",
                            AssignedTo = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Report",
                            CreatedAt = new DateTime(2026, 6, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "dedi.kurniawan@customer.com",
                            CustomerName = "Dedi Kurniawan",
                            CustomerPhone = "0812-3456-7809",
                            Description = "Tombol export ke Excel di halaman laporan tidak merespon saat diklik.",
                            Impact = "SomeUsers",
                            Priority = "Medium",
                            Status = "InProgress",
                            TicketNumber = "TKT-00009",
                            Title = "Fitur tidak berfungsi",
                            Type = "Incident"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            Application = "ERP",
                            AssignedTo = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Report",
                            CreatedAt = new DateTime(2026, 6, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "admin@globalinti.com",
                            CustomerName = "PT. Global Inti",
                            CustomerPhone = "021-5559876",
                            Description = "Membutuhkan laporan rekap transaksi bulanan dalam format PDF untuk keperluan internal.",
                            Impact = "SingleUser",
                            Priority = "Low",
                            Status = "Open",
                            TicketNumber = "TKT-00010",
                            Title = "Permintaan laporan bulanan",
                            Type = "ServiceRequest"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            Application = "None",
                            Category = "Hardware",
                            CreatedAt = new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "amel.marsha@customer.com",
                            CustomerName = "Amel Marsha",
                            CustomerPhone = "0812-3456-7811",
                            Description = "Beberapa tombol pada keyboard laptop tidak berfungsi, khususnya tombol angka.",
                            Impact = "SingleUser",
                            Priority = "Medium",
                            Status = "Open",
                            TicketNumber = "TKT-00011",
                            Title = "Keyboard laptop rusak",
                            Type = "Incident"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            Application = "HRIS",
                            AssignedTo = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Application",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerEmail = "nanda.triana@customer.com",
                            CustomerName = "Nanda Triana",
                            CustomerPhone = "0812-3456-7812",
                            Description = "Permintaan penambahan field baru 'Nomor BPJS' pada modul data karyawan.",
                            Impact = "SomeUsers",
                            Priority = "Low",
                            Status = "Resolved",
                            TicketNumber = "TKT-00012",
                            Title = "Perubahan konfigurasi sistem HR",
                            Type = "ChangeRequest"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Action = "TicketCreated",
                            ChangedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Ticket created by Admin User.",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Timestamp = new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Action = "AssigneeChanged",
                            ChangedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 1, 9, 15, 0, 0, DateTimeKind.Utc),
                            NewValue = "Andi Pratama",
                            OldValue = "Unassigned",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Timestamp = new DateTime(2026, 7, 1, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Action = "TicketCreated",
                            ChangedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Ticket created by Admin User.",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Timestamp = new DateTime(2026, 6, 30, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Action = "PriorityChanged",
                            ChangedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            NewValue = "Medium",
                            OldValue = "Low",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Timestamp = new DateTime(2026, 6, 30, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 30, 11, 0, 0, 0, DateTimeKind.Utc),
                            NewValue = "InProgress",
                            OldValue = "Open",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Timestamp = new DateTime(2026, 6, 30, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Action = "CommentAdded",
                            ChangedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Note = "User sudah mencoba solusi tetapi masih gagal.",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Timestamp = new DateTime(2026, 6, 30, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Action = "TicketCreated",
                            ChangedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Ticket created by Admin User.",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Timestamp = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            NewValue = "InProgress",
                            OldValue = "Open",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Timestamp = new DateTime(2026, 6, 27, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 28, 7, 0, 0, 0, DateTimeKind.Utc),
                            NewValue = "Resolved",
                            OldValue = "InProgress",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Timestamp = new DateTime(2026, 6, 28, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000a"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            NewValue = "Closed",
                            OldValue = "Resolved",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Timestamp = new DateTime(2026, 6, 28, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000b"),
                            Action = "TicketCreated",
                            ChangedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Ticket created by Admin User.",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Timestamp = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000c"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            NewValue = "Closed",
                            OldValue = "Open",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Timestamp = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000d"),
                            Action = "TicketCreated",
                            ChangedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Ticket created by Admin User.",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Timestamp = new DateTime(2026, 6, 27, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000e"),
                            Action = "AssigneeChanged",
                            ChangedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 27, 9, 10, 0, 0, DateTimeKind.Utc),
                            NewValue = "Andi Pratama",
                            OldValue = "Unassigned",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Timestamp = new DateTime(2026, 6, 27, 9, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000f"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            NewValue = "InProgress",
                            OldValue = "Open",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Timestamp = new DateTime(2026, 6, 27, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            Action = "TicketCreated",
                            ChangedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Ticket created by Admin User.",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Timestamp = new DateTime(2026, 6, 24, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            NewValue = "Closed",
                            OldValue = "Open",
                            TicketId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Timestamp = new DateTime(2026, 6, 24, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Jl. Jenderal Sudirman No. 10, Jakarta Pusat, DKI Jakarta",
                            CreatedAt = new DateTime(2026, 6, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@company.com",
                            IsActive = true,
                            JobTitle = "System Administrator",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$P/lO7CA.41oXAOsFw16J7Ox2IRJlctUf2/RxorywWvWOMxzrBDgFu",
                            PhoneNumber = "0812-3456-7890",
                            Role = "Manager",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andi.pratama@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Andi Pratama",
                            PasswordHash = "$2a$11$kQDRxqXy24ItokVig6Ge0.NSZqIjjCKh9DmLVF5kzYyHN3J4nydb2",
                            PhoneNumber = "0812-3456-7891",
                            Role = "SupportAgent",
                            Username = "andi.pratama"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "siti.aisyah@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Siti Aisyah",
                            PasswordHash = "$2a$11$jF/rAxZyePzqQnsHJb4xXe6E0CekI8K7y5bzsDYyfTHMxSmfLaXh6",
                            PhoneNumber = "0812-3456-7892",
                            Role = "SupportAgent",
                            Username = "siti.aisyah"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "budi.santoso@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Budi Santoso",
                            PasswordHash = "$2a$11$J9ffXjeUV/PACSWRRDxTn.jYKYypdk.dKXOYZVNISLz/j5401GaDe",
                            PhoneNumber = "0812-3456-7893",
                            Role = "SupportAgent",
                            Username = "budi.santoso"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dewi.lestari@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Dewi Lestari",
                            PasswordHash = "$2a$11$UHJd5eSVGaLFa3bpBXBV5ue.Jqxz8kFF2TAFzAxFWcYmYUquCoGpu",
                            PhoneNumber = "0812-3456-7894",
                            Role = "SupportAgent",
                            Username = "dewi.lestari"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 6, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "rizky.hidayat@company.com",
                            IsActive = true,
                            JobTitle = "Support Agent",
                            Name = "Rizky Hidayat",
                            PasswordHash = "$2a$11$FSnmWqH5vkJDg1IFtPPQvOk/SgMSr6ARbwA8b8ADUrg2aNCepB6S2",
                            PhoneNumber = "0812-3456-7895",
                            Role = "SupportAgent",
                            Username = "rizky.hidayat"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nanda.triana@company.com",
                            IsActive = true,
                            JobTitle = "Support Manager",
                            Name = "Nanda Triana",
                            PasswordHash = "$2a$11$Yo9SofrKhyU4vVaejPQ16OYucZMI04I8RR30YNbeVgsv8coiNQay.",
                            PhoneNumber = "0812-3456-7896",
                            Role = "Manager",
                            Username = "nanda.triana"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "support@company.com",
                            IsActive = false,
                            Name = "Support Team",
                            PasswordHash = "$2a$11$xtNKlJJXlNTvjmesK63KVeQAy6DWfrLB/9LfaYoesUkY/yfEtWr0u",
                            Role = "SupportAgent",
                            Username = "support.team"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportTicketSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Histories")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
