// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTicketSystem.Infrastructure.Persistence;

#nullable disable

namespace SupportTicketSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723080154_bCryptInDataSeed")]
    partial class bCryptInDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedDate", "Status", "AssignedTo");

                    b.ToTable("Tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 22, 8, 1, 47, 747, DateTimeKind.Utc).AddTicks(9397),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "john@client.com",
                            CustomerName = "John Doe",
                            Description = "Urgent: Server is not responding.",
                            Status = "Open",
                            TicketNumber = "TKT-00001",
                            Title = "System Down"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 22, 20, 1, 47, 747, DateTimeKind.Utc).AddTicks(9423),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "jane@client.com",
                            CustomerName = "Jane Smith",
                            Description = "Button color is wrong on dark mode.",
                            Status = "InProgress",
                            TicketNumber = "TKT-00002",
                            Title = "UI Bug"
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 20, 8, 1, 47, 747, DateTimeKind.Utc).AddTicks(9427),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "mark@client.com",
                            CustomerName = "Mark Lee",
                            Description = "User forgot password.",
                            Status = "Closed",
                            TicketNumber = "TKT-00003",
                            Title = "Password Reset"
                        },
                        new
                        {
                            Id = new Guid("09fdbcb2-3f03-4c45-9bfc-c54de8145340"),
                            AssignedTo = new Guid("e5f6a7b8-c9d0-4e1f-b2a3-b4c5d6e7f8a9"),
                            CreatedAt = new DateTime(2026, 7, 23, 3, 1, 47, 747, DateTimeKind.Utc).AddTicks(9467),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "emily@client.com",
                            CustomerName = "Emily Blunt",
                            Description = "Credit card rejected.",
                            Status = "InProgress",
                            TicketNumber = "TKT-00004",
                            Title = "Payment Issue"
                        },
                        new
                        {
                            Id = new Guid("f79549fc-b5bb-4542-a636-958b3645ecec"),
                            AssignedTo = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 21, 8, 1, 47, 747, DateTimeKind.Utc).AddTicks(9472),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "kevin@client.com",
                            CustomerName = "Kevin Hart",
                            Description = "CSV export is empty.",
                            Status = "Resolved",
                            TicketNumber = "TKT-00005",
                            Title = "Export Failure"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e869b1fd-98ec-4491-91a4-0e2ea26774a3"),
                            Action = "Created",
                            ChangedBy = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 47, 748, DateTimeKind.Local).AddTicks(7041),
                            NewStatus = "Open",
                            TicketId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 7, 22, 8, 1, 47, 748, DateTimeKind.Utc).AddTicks(7073)
                        },
                        new
                        {
                            Id = new Guid("13e1575d-40d2-48de-8546-d6c82e1a139a"),
                            Action = "Assigned",
                            ChangedBy = new Guid("c3d4e5f6-a7b8-4c9d-8e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 47, 748, DateTimeKind.Local).AddTicks(7077),
                            NewStatus = "InProgress",
                            TicketId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            Timestamp = new DateTime(2026, 7, 22, 22, 1, 47, 748, DateTimeKind.Utc).AddTicks(7092)
                        },
                        new
                        {
                            Id = new Guid("f6fad12f-a598-4c26-85a8-138a1c5a13ed"),
                            Action = "StatusChanged",
                            ChangedBy = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 47, 748, DateTimeKind.Local).AddTicks(7094),
                            NewStatus = "Closed",
                            PreviousStatus = "InProgress",
                            TicketId = new Guid("e3333333-3333-3333-3333-333333333333"),
                            Timestamp = new DateTime(2026, 7, 23, 6, 1, 47, 748, DateTimeKind.Utc).AddTicks(7099)
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 47, 749, DateTimeKind.Local).AddTicks(336),
                            Email = "azwar@support.com",
                            Name = "Azwar Manager",
                            PasswordHash = "$2a$11$Ep20NleMyZlU1PIkINzuIOlH63jAP7KfcYEc4d/hbHGIudfzlXBQe",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-8e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 47, 898, DateTimeKind.Local).AddTicks(1952),
                            Email = "sarah.m@support.com",
                            Name = "Sarah Miller",
                            PasswordHash = "$2a$11$lGT1JtyDXi3Up.pbWJeRc.OuNoRwHBtNLAxOcrCKums.Eyul7DYTq",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-9f2a-3b4c5d6e7f8a"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 48, 44, DateTimeKind.Local).AddTicks(3490),
                            Email = "david.c@support.com",
                            Name = "David Chen",
                            PasswordHash = "$2a$11$1.f2a.gYHSsDUL.G47tky.lG/kbwh35SDFofSkWzvP4em/lFR.koq",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 48, 192, DateTimeKind.Local).AddTicks(3979),
                            Email = "budi@support.com",
                            Name = "Budi Agent",
                            PasswordHash = "$2a$11$82prow65i7.SEcYSyn0i7uMbTY9Ud/Fsm05DornsZG7PtdDc.1DvK",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-b2a3-b4c5d6e7f8a9"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 48, 349, DateTimeKind.Local).AddTicks(9803),
                            Email = "alice.j@support.com",
                            Name = "Alice Johnson",
                            PasswordHash = "$2a$11$gblKbK/eaOLhp6EPtZujNeVYjl4GUp.Gk7Hqcp.UawTYOOSpT.8Yq",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4f2a-c3b4-c5d6e7f8a9b0"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 48, 497, DateTimeKind.Local).AddTicks(2880),
                            Email = "robert.s@support.com",
                            Name = "Robert Smith",
                            PasswordHash = "$2a$11$yX9wSQsSoO1wVsw6jL1kW.V8yoWvMOc8iUk/9NMB15a5wFMs52bvm",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 48, 646, DateTimeKind.Local).AddTicks(7055),
                            Email = "emily.d@support.com",
                            Name = "Emily Davis",
                            PasswordHash = "$2a$11$Cgncj7D9UZ.mla3vluy01uJ19XSgMI4bXnRpmtKwN.xhDGukDIQQK",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("1b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 48, 792, DateTimeKind.Local).AddTicks(9796),
                            Email = "michael.b@support.com",
                            Name = "Michael Brown",
                            PasswordHash = "$2a$11$PVSX39rMDRrX2yOSrW0NM.9j5sFi3AOgPgm4eWaxGcN3tORoH0Hu6",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 48, 951, DateTimeKind.Local).AddTicks(6288),
                            Email = "jessica.w@support.com",
                            Name = "Jessica Wilson",
                            PasswordHash = "$2a$11$.rGA6a/gfUy7BdoZRf/sWuRCju5Tc73SADDVPxS/DSJ.AUtZDE2Ue",
                            Role = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("3d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
                            CreatedAt = new DateTime(2026, 7, 23, 15, 1, 49, 104, DateTimeKind.Local).AddTicks(6026),
                            Email = "kevin.l@support.com",
                            Name = "Kevin Lee",
                            PasswordHash = "$2a$11$lYJsxB4vZXqCOQVI3UBcxuCdeR1XqF5Jqzive5TSLPxlAfSWdoxAK",
                            Role = "SupportAgent"
                        });
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("SupportTicketSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportTicketSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTicketSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
